export const tiles = [
  {
    id: "1",
    title: "Bio",
    desc: "Steve Kretz - Realistic Tattoo Artist: My Story.",
    ref: "/bio",
    src: "",
  },
  {
    id: "2",
    title: "Portfolio",
    desc: "Recent Tattoos done in a mix of styles.",
    ref: "/portfolio",
    src: "",
  },
  {
    id: "3",
    title: "Available Art",
    desc: "Ideas and art that are available now to tattoo.",
    ref: "/availableart",
    src: "",
  },
  {
    id: "4",
    title: "Blog",
    desc: "What's been going on with me and all the news.",
    ref: "/blog",
    src: "",
  },
  {
    id: "5",
    title: "Contact/Booking",
    desc: "Let's talk booking and contact! ",
    ref: "/contactbooking",
    src: "",
  },
  {
    id: "6",
    title: "Secret Club",
    desc: "Sign up to the mailing list for fresh new art and regular promotions.",
    ref: "/mailing",
    src: "",
  },
  {
    id: "7",
    title: "Aftercare",
    desc: "Got your tattoo done? Here is where you'll find all about how to care for it after.",
    ref: "/aftercare",
    src: "",
  },
      {
        id: "8",
        title: "FAQs",
        desc: "A small amount of the most questions I receive answered",
        ref: "/faqs",
        src: "",
    },
];
